name: 'Build and Test'

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      
      - name: Validate wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
    
      - name: Copy together artifacts
        shell: bash
        run: |
          mkdir dist
          cp build/libs/*.jar dist

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: dist/*

      - name: Upload JAR to existing release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.jar  # JARファイルをアップロード
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
